version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
      commit-message:
          prefix: "[ci skip]"
